+incdir+/home/ltthinh/CLAUDE_PRO/src/rtl
/home/ltthinh/CLAUDE_PRO/src/rtl/rv32im_pkg.sv
/home/ltthinh/CLAUDE_PRO/src/rtl/rv32im_alu.sv
/home/ltthinh/CLAUDE_PRO/src/rtl/rv32im_branch_unit.sv
/home/ltthinh/CLAUDE_PRO/src/rtl/rv32im_imm_gen.sv
/home/ltthinh/CLAUDE_PRO/src/rtl/rv32im_decoder.sv
/home/ltthinh/CLAUDE_PRO/src/rtl/rv32im_lsu.sv
/home/ltthinh/CLAUDE_PRO/src/rtl/rv32im_regfile.sv
/home/ltthinh/CLAUDE_PRO/src/rtl/rv32im_mult.sv
/home/ltthinh/CLAUDE_PRO/src/rtl/rv32im_div.sv
/home/ltthinh/CLAUDE_PRO/src/rtl/rv32im_muldiv.sv
/home/ltthinh/CLAUDE_PRO/src/rtl/rv32im_hazard_ctrl.sv
/home/ltthinh/CLAUDE_PRO/src/rtl/rv32im_if_stage.sv
/home/ltthinh/CLAUDE_PRO/src/rtl/rv32im_id_stage.sv
/home/ltthinh/CLAUDE_PRO/src/rtl/rv32im_ex_stage.sv
/home/ltthinh/CLAUDE_PRO/src/rtl/rv32im_csr_file.sv
/home/ltthinh/CLAUDE_PRO/src/rtl/rv32im_trap_ctrl.sv
/home/ltthinh/CLAUDE_PRO/src/rtl/rv32im_mem_stage.sv
/home/ltthinh/CLAUDE_PRO/src/rtl/rv32im_core.sv
